name = "sfcraft"
author = "iceBear67"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24c62372188222bf547256a24c35f395d6addeaa74c3f8cc0dd69c4a8c793a66"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = ["26.3"]
