name = "sfcraft"
author = "iceBear67"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "716a1dec38a348bd1a18887580bd9e19325b2d65bdfb937e5dc2d058dcd9ccb8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1", "26.1.2"]
