# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy to server

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle 8.10
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.10" # Quotes required to prevent YAML converting to number

    - name: Build with Gradle Wrapper
      run: gradle remapJar
    - name: Install JQ
      uses: dcarbone/install-jq-action@v2.1.0
    - name: Upload Artifact
      env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        SERVER_ID: ${{ secrets.SERVER_ID }}
        TOKEN: ${{ secrets.TOKEN }}
        UPLOAD_DIR: "../build/libs"
      run: |
        cd scripts
        chmod +x ./special_curl
        sh ./update.sh
